vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        categories:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        productImages:
            uri_prefix: /product-images
            upload_destination: '%kernel.project_dir%/public/product-images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            

    #    products:
    #        uri_prefix: /images/products (ici c'est a le prefixe à mettre en coherence avec le dossier destionation d'upload ** pas de majuscule**)
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
